# Generated by Django 5.2.4 on 2025-11-23 00:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='temporadas',
        ),
        migrations.DeleteModel(
            name='Temporada',
        ),
        migrations.AddField(
            model_name='producto',
            name='temporadas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('verano', 'Verano'), ('otoño', 'Otoño'), ('invierno', 'Invierno'), ('primavera', 'Primavera')], max_length=31),
        ),
    ]
