# Generated by Django 5.2.4 on 2025-11-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_producto_temporadas_delete_temporada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuestra_historia', models.TextField(blank=True)),
                ('nuestros_valores', models.TextField(blank=True)),
                ('origen_productos', models.TextField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido institucional',
                'verbose_name_plural': 'Contenido institucional',
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('horario', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('link_mapa', models.URLField(blank=True, help_text='Link a Google Maps (opcional)')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
