# Generated by Django 5.2.4 on 2025-12-03 16:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_alter_producto_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="temporadas",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("verano", "Verano"),
                    ("otoño", "Otoño"),
                    ("invierno", "Invierno"),
                    ("primavera", "Primavera"),
                ],
                max_length=50,
            ),
        ),
    ]
