# Generated by Django 5.2.4 on 2025-12-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='tipo',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('temporal', 'Temporal')], default='fijo', help_text="Fijo: se muestra en el footer. Temporal: solo en la página 'Quiénes somos'", max_length=10),
        ),
    ]
